[package]
name = "day1"
version = "0.1.0"
authors = ["Costas Akrivoulis <gr33kdude@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"

[[bin]]
name = "day1"
path = "main.rs"
